server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: movie_user
    password: movie_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 960166939820-jk4j2t4b8un08fqbmhvp05ctqebb8oeo.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: MovieBackendSecretKey
api:
  secret: "43dd2ba4"
fetch:
  interval: 60000

